---
# Namespace under which applications will run if connected
string application_namespace

# Who is controlling the app manager (i.e. who invited it to send it's
# control handles). If the empty string, it is not being controlled 
# and subsequently is available
string remote_controller

# Current app status, stopped or running
string app_status

