# Provides platform details from the app manager.

######################## Platform Triple ########################

string PLATFORM_ANY=*
string PLATFORM_LINUX=linux
string PLATFORM_WINDOZE=windoze
string PLATFORM_ANDROID=android

string SYSTEM_CUSTOM=custom
string SYSTEM_ROS=ros
string SYSTEM_OPROS=opros

# Valid robot types, though this is totally not
# official, and we aren't relying on it.
string ROBOT_ANY=*
string ROBOT_PC=pc
string ROBOT_ROBOSEM=robosem
string ROBOT_KOBUKI=kobuki
string ROBOT_TURTLEBOT=turtlebot

########################### Variables ###########################

string platform
string system
string robot
string name
